function [KIJ]=KK(y1_Crossed, y2_Crossed, y3_Crossed, y1, y2, y3)

	KIJ = (y2_Crossed - y3_Crossed) * ...
    	(y1_Crossed - y3_Crossed) + ...
    	Cross_mex((y2_Crossed * y1')') - ...
    	Cross_mex((y2_Crossed * y3')') - ...
    	Cross_mex((y3_Crossed * y1')');

end